blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/stratix-dev/stratix/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://stratix-dev.github.io/stratix
    about: Check the documentation for help
